source: ./docs/
exclude: [_babel, src, ds4.browser.json, ds6.browser.json]
highlighter: rouge
url: https://ebay.github.io/skin
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cdn_path: https://ir.ebaystatic.com/cr/v/c1/skin
<<<<<<< HEAD
      version: 10.6.0-0
=======
      version: 10.5.2
>>>>>>> d12a179b3fc0d6005541ed5239b8b9f11a34c589
